# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(upload_to='images/banner/%Y/%m/', verbose_name='广告轮播图')),
                ('img_alt', models.CharField(max_length=100, verbose_name='轮播图提示')),
                ('img_position', models.IntegerField(verbose_name='广告顺序')),
                ('link', models.CharField(max_length=255, verbose_name='广告链接')),
            ],
            options={
                'verbose_name': '广告轮播',
                'verbose_name_plural': '广告轮播',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(default='images/blog/default.jpg', upload_to='images/blog/%Y/%m/', verbose_name='封面图')),
                ('img_alt', models.CharField(max_length=50, verbose_name='封面图描述')),
                ('title', models.CharField(max_length=200, verbose_name='博客标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('edit_time', models.DateTimeField(auto_now_add=True, verbose_name='修改日期')),
                ('look_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('keep_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('digg_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('content', models.TextField(verbose_name='博文内容')),
            ],
        ),
        migrations.CreateModel(
            name='Categray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
    ]
