# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180517_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='CvejGsnR', max_length=50, verbose_name='昵称'),
        ),
    ]
